version: '3.9'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    networks:
      - dostavkaNetwork

  dostavka:
    container_name: dostavka
    image: adassh/dostavka:v3
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - dostavkaNetwork

networks:
  dostavkaNetwork:
